apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
spec:
  version: 7.10.1
  count: 1
  elasticsearchRef:
    name: elasticsearch-cluster
    namespace: default
  kibanaRef:
    name: kibana-cluster